name: 'CI Validate Production'
author: 'ndrewr'
description: 'Authenticates to Production org using SFDX cli tool'

inputs:
  auth-file-key:
    description: 'Auth key to Prod org'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.auth-file-key }}
    - ${{ inputs.target-alias }}

