public with sharing class heyPackageController {
    public static Integer getRandomNumber() {
        return 7;
    }

    public static String getRandomText() {
        return 'Some totally random text.';
    }

    public static String getRandomText2() {
        return 'Some totally more random text.';
    }

    public static String getRandomText3() {
        return 'Some totally even more random text.';
    }
}
