on:
    push:
        branches:
            - master
            - feature1
            - feature2

jobs:
    task_one:
        runs-on: ubuntu-latest
        name: Lets run the second task
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Run some more commands for test purposes
              id: ci-cd
              uses: tythonco/actions-sfdx/ci-cd@master
